import { CarePlan } from '@/types/carePlan';

export const generateMockCarePlan = (): Omit<CarePlan, 'status'> => ({
  id: crypto.randomUUID(),
  patientId: crypto.randomUUID(),
  title: 'Genel Sağlık İyileştirme Planı',
  description: 'Hastanın genel sağlık durumunu iyileştirmeye yönelik kapsamlı plan.',
  startDate: new Date(),
  endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  medications: [
    {
      id: crypto.randomUUID(),
      name: 'Vitamin D3',
      dosage: 1000,
      unit: 'mg',
      frequency: 'daily',
      startDate: new Date(),
      instructions: 'Kahvaltıdan sonra alınmalı',
      reminder: true,
      notifyBeforeMinutes: 30,
    },
    {
      id: crypto.randomUUID(),
      name: 'Omega 3',
      dosage: 500,
      unit: 'mg',
      frequency: 'daily',
      startDate: new Date(),
      instructions: 'Akşam yemeğinden sonra alınmalı',
      reminder: true,
      notifyBeforeMinutes: 30,
    },
  ],
  appointments: [
    {
      id: crypto.randomUUID(),
      title: 'Rutin Kontrol',
      type: 'checkup',
      date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      duration: 30,
      location: 'Ana Klinik',
      doctorName: 'Dr. Ayşe Yılmaz',
      reminder: true,
      notifyBeforeMinutes: 60,
    },
  ],
  goals: [
    {
      id: crypto.randomUUID(),
      title: 'Günlük Yürüyüş',
      description: 'Her gün en az 30 dakika tempolu yürüyüş',
      targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      targetValue: 30,
      unit: 'dakika',
      status: 'in_progress',
      category: 'exercise',
      reminder: true,
      checkInFrequency: 'daily',
    },
    {
      id: crypto.randomUUID(),
      title: 'Su Tüketimi',
      description: 'Günde en az 2 litre su içmek',
      targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      targetValue: 2,
      unit: 'litre',
      status: 'in_progress',
      category: 'nutrition',
      reminder: true,
      checkInFrequency: 'daily',
    },
  ],
  metrics: [
    {
      id: crypto.randomUUID(),
      name: 'Kan Basıncı',
      type: 'number',
      unit: 'mmHg',
      frequency: 'daily',
      reminder: true,
      notifyBeforeMinutes: 0,
      description: 'Günlük kan basıncı ölçümü',
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
});
